<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_news_model extends CI_Model
{

    public $table = 'tbl_news';
    public $id = 'news_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('news_id', $q);
	$this->db->or_like('news_title', $q);
	$this->db->or_like('news_content', $q);
	$this->db->or_like('news_content_short', $q);
	$this->db->or_like('news_date', $q);
	$this->db->or_like('photo', $q);
	$this->db->or_like('banner', $q);
	$this->db->or_like('category_id', $q);
	$this->db->or_like('comment', $q);
	$this->db->or_like('meta_title', $q);
	$this->db->or_like('meta_keyword', $q);
	$this->db->or_like('meta_description', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('news_id', $q);
	$this->db->or_like('news_title', $q);
	$this->db->or_like('news_content', $q);
	$this->db->or_like('news_content_short', $q);
	$this->db->or_like('news_date', $q);
	$this->db->or_like('photo', $q);
	$this->db->or_like('banner', $q);
	$this->db->or_like('category_id', $q);
	$this->db->or_like('comment', $q);
	$this->db->or_like('meta_title', $q);
	$this->db->or_like('meta_keyword', $q);
	$this->db->or_like('meta_description', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_news_model.php */
/* Location: ./application/models/Tbl_news_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-30 04:07:46 */
/* http://harviacode.com */