<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_page_contact_model extends CI_Model
{

    public $table = 'tbl_page_contact';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id,contact_heading,contact_address,contact_email,contact_phone,contact_map,mt_contact,mk_contact,md_contact');
        $this->datatables->from('tbl_page_contact');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_page_contact.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('tbl_page_contact/update/$1'), '<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm waves-effect waves-themed')), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('contact_heading', $q);
        $this->db->or_like('contact_address', $q);
        $this->db->or_like('contact_email', $q);
        $this->db->or_like('contact_phone', $q);
        $this->db->or_like('contact_map', $q);
        $this->db->or_like('mt_contact', $q);
        $this->db->or_like('mk_contact', $q);
        $this->db->or_like('md_contact', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('contact_heading', $q);
        $this->db->or_like('contact_address', $q);
        $this->db->or_like('contact_email', $q);
        $this->db->or_like('contact_phone', $q);
        $this->db->or_like('contact_map', $q);
        $this->db->or_like('mt_contact', $q);
        $this->db->or_like('mk_contact', $q);
        $this->db->or_like('md_contact', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Tbl_page_contact_model.php */
/* Location: ./application/models/Tbl_page_contact_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-30 04:33:05 */
/* http://harviacode.com */
